// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// Foo depends on Message, Fizz, and Buzz.
// wire.Struct(new(Foo), "Bar", "Baz", "Qux") tells Wire to inject these fields
// by finding providers that return the matching types.
func InitializeFoo() (*Foo, error) {
	message := NewMessage()
	fizz := NewFizz()
	buzz := NewBuzz()
	foo := &Foo{
		Bar: message,
		Baz: fizz,
		Qux: buzz,
	}
	return foo, nil
}
