// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeInjector() (*Injector, error) {
	mainMessageService := NewMessageService()
	injector := &Injector{
		MessageService: mainMessageService,
	}
	return injector, nil
}

// wire.go:

// Injector 所有 provider 的统一注入器
type Injector struct {
	MessageService MessageService
}
