// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// InitializeBar wires the Fooer interface to MyFooer implementation.
func InitializeBar() (*Bar, error) {
	myFooer := ProvideMyFooer()
	bar := ProvideBar(myFooer)
	return bar, nil
}

// wire.go:

// ProvideMyFooer creates a MyFooer instance.
func ProvideMyFooer() *MyFooer {
	return &MyFooer{}
}

// ProvideBar creates a Bar with a Fooer.
func ProvideBar(f Fooer) *Bar {
	return &Bar{Foo: f}
}
