// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// InitializeInjector is the wire entry point. cfgPath is accepted for
// symmetry with ProvideRedisClient(cfgPath) but only the type graph is
// resolved here; cfgPath is consumed at runtime by the test harness.
func InitializeInjector(cfgPath string) (*Injector, error) {
	cachexProvider := NewCachexProvider()
	injector := &Injector{
		Cache: cachexProvider,
	}
	return injector, nil
}

// wire.go:

// Injector carries the providers used by tests.
type Injector struct {
	Cache *CachexProvider
}
