// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// InitializeInjector 带输入参数的注入器
// Wire 会自动将 Config 参数传递给需要它的 Provider
func InitializeInjector(cfg Config) (*Injector, error) {
	mainMessageService := NewMessageService(cfg)
	injector := &Injector{
		MessageService: mainMessageService,
	}
	return injector, nil
}

// wire.go:

// Injector 所有 provider 的统一注入器
type Injector struct {
	MessageService MessageService
}
