// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// InjectMessage demonstrates wire.FieldsOf - using struct fields as providers.
// wire.FieldsOf extracts field values from a provided struct and makes them
// available as dependencies. In this example, Foo is provided with hardcoded
// values, then wire.FieldsOf extracts its Bar, Baz, Qux fields as providers.
func InjectMessage() (*Message, error) {
	foo := ProvideFoo()
	bar := foo.Bar
	baz := foo.Baz
	qux := foo.Qux
	message := &Message{
		Bar: bar,
		Baz: baz,
		Qux: qux,
	}
	return message, nil
}
