// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeInjector() (*Injector, error) {
	string2 := _wireStringValue
	int2 := _wireIntValue
	database, err := NewDatabase(string2, int2)
	if err != nil {
		return nil, err
	}
	cache, err := NewCache()
	if err != nil {
		return nil, err
	}
	logger, err := NewLogger(string2)
	if err != nil {
		return nil, err
	}
	injector := &Injector{
		Database: database,
		Cache:    cache,
		Logger:   logger,
	}
	return injector, nil
}

var (
	_wireStringValue = "localhost"
	_wireIntValue    = 5432
)

// wire.go:

// ProviderSet 将多个 Provider 分组
var ProviderSet = wire.NewSet(
	NewDatabase,
	NewCache,
	NewLogger,
)

// Injector 所有 provider 的统一注入器
type Injector struct {
	Database Database
	Cache    Cache
	Logger   Logger
}
