// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// InitializeService creates a ServiceOwner with its cleanup function.
func InitializeService() (*ServiceOwner, error) {
	database := NewDatabase()
	cache := NewCache()
	service := NewService(database, cache)
	cleanupFunc, err := newCleanupFunc(service)
	if err != nil {
		return nil, err
	}
	serviceOwner := &ServiceOwner{
		Service: service,
		Cleanup: cleanupFunc,
	}
	return serviceOwner, nil
}
