// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// InitializeInjector Wire 自动注入
func InitializeInjector() (*Injector, error) {
	mainGreeter := NewGreeter()
	mainInjector := &Injector{
		Greeter: mainGreeter,
	}
	return mainInjector, nil
}

// wire.go:

// Injector 所有 provider 的统一注入器
type Injector struct {
	Greeter Greeter
}
